numeros = [1,2,3,4,0.5,1.3,9.9,6.7]
print(numeros)
print(len(numeros))
print(numeros[4])
numeros.append(7)
numeros.append(8)
numeros.append(10)
print(numeros)
numeros.insert(6,66)
print(numeros)
numeros.remove(7)
print(numeros)
print(len(numeros))
print(sum(numeros))
media = sum(numeros) / len(numeros)
print(f"{media:.2f}")
numeros.sort()
print(numeros)
numeros.sort(reverse=True)
print(numeros)
print(min(numeros))
print(max(numeros))